### ISSUE TITLE
Include welsh translation of writing guidelines

### ISSUE THREAD

**Issue by geraintpalmer** [drvinceknight/cfm#101]
@geraintpalmer has .tex / .pdf

**Comment by drvinceknight** [comment]
@geraintpalmer can you drag and drop the tex and pdf files here please?

**Comment by geraintpalmer** [comment]
[canllawiau.pdf](https://github.com/drvinceknight/cfm/files/2603774/canllawiau.pdf)

**Comment by geraintpalmer** [comment]
[canllawiau.txt](https://github.com/drvinceknight/cfm/files/2603785/canllawiau.txt)


(Github issues doesn't support .tex files, so I just changed the suffix to .txt)

**Comment by drvinceknight** [comment]
Diolch! :+1:
