### ISSUE TITLE
Peer review (NO RUSH - low priority)

### ISSUE THREAD

**Issue by drvinceknight** [drvinceknight/cfm#94]
@Nikoleta-v3 and @daffidwilde, when you get a chance could you read through the updated course site: https://vknight.org/cfm/

Everything is tested so I'm not overly worried about code being correct (but by all means let me know if you spot anything), specific things I'd appreciate you looking through:

- These two chapters are new (ish): https://vknight.org/cfm/chapters/05/ and https://vknight.org/cfm/chapters/06/
- The assessment document: https://vknight.org/cfm/other/assessment/
- The docs document for tutors: https://vkcfm.readthedocs.io/en/latest/tutors/index.html

**Please don't spend much time on this.**

**Comment by Nikoleta-v3** [comment]
I am loving the little summary before the exercises :+1:

**Comment by Nikoleta-v3** [comment]
I open a pull request for the trivial stuff. Here are some further comments.

Chapter 3
-----------

>>> Strings (see in in the previous lab sheet) and lists are similar in that they are 'containers' for items. A lot of the manipulation that works with lists also works with strings:

It is no immediate to me why you are reminding me of this. You end the sentence with `:`. Are you missing something or is it just a typo?

Would you like to include something for the round function on cell 13? _Not very important_.

Chapter 4
-------------

- The link for `A nice tutorial: a role playing example` is broke. 

Chapter 6
------------
My blog post made it here :tada: 

Overall
----------
You refer to Python as Python and python. Not very important but it would be nice to be consistent.

**Comment by drvinceknight** [comment]
@Nikoleta-v3: awesome thank you, I'll go ahead and fix all those (no need for a PR). :+1:
